name: Fetch Secret into Python Script
on: 
  workflow_dispatch: # push # manual trigger for now

jobs:
  fetch-and-run:
    runs-on: ubuntu-latest # environment 

    steps: 
      - name: Checkout code #Step 1 - fetch code repo
        uses: actions/checkout@v4 

      - name: set up Python # Step 2 - Prepare python environment
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install pymongo 
          pip install google-genai

      - name: Run Python Script # Step 3 - Execute script with API key and DB secrets
        env: 
          API_KEY: ${{ secrets.GEMINI_CANARY_KEY }} # fetch API key
          ENV_DB: ${{ secrets.CHANGE_STREAM_DB }} # fetch MongoDB connection string
        run: python gemini.py
